apiVersion: v2
name: resilience-lab
description: A Kubernetes resilience sandbox for trsting cloud-native failure patterns
type: application
version: 0.1.0
appVersion: "1.0"
maintainers:
  - name: resilience-lab-team
    email: andii4444@gmail.com
dependencies:
  - name: api
    version: "0.1.0"
    repository: "file://./charts/api"
  - name: payments
    version: "0.1.0"
    repository: "file://./charts/payments"
